### ISSUE TITLE
存在无法添加外键的问题

### ISSUE THREAD

**Issue by lyha23** [kexue-z/nonebot-plugin-tortoise-orm#1]
使用该orm需要指定module，否则无法添加外键
<img width="979" alt="截屏2022-08-24 17 05 11" src="https://user-images.githubusercontent.com/75962592/186377944-550f63db-6b05-4e54-87e2-561faf525475.png">

**Comment by lyha23** [comment]
搞错了，不好意思。模型的应用名就是models，我以为还需要一些单独的配置
<img width="830" alt="截屏2022-08-24 18 26 11" src="https://user-images.githubusercontent.com/75962592/186395726-22e54903-a850-4ab1-be98-c47edc927f5f.png">

**Comment by kexue-z** [comment]
我还一脸懵逼以为你要怎么用~
