### ISSUE TITLE
数据库以及签到使用问题

### ISSUE THREAD

**Issue by mintianzan** [kexue-z/nonebot-plugin-tortoise-orm#2]
您好，我在使用tortoise-orm以及dailysign的过程中遇到如下问题：
![微信截图_20230906112047](https://github.com/kexue-z/nonebot-plugin-tortoise-orm/assets/140377173/cd676842-685b-402a-99e1-60bbe2479483)
（在使用example的时候同样遇到了tortoise.exceptions.DoesNotExist: Object does not exist的问题，如果两个问题无关的话我之后再补上log）
我认为可能是由于我并没有利用pip来安装这两个插件，而是直接解压到plugins目录来使用造成的。
如果原因的确如此的话，我想问一下如果自己编写需要用到tortoise-orm的插件的话，会不会遇到同样的问题？因为自己写的插件可能并不会被tortoise的import检测到？还是说需要把plugins文件夹设置成环境变量？

**Comment by kexue-z** [comment]
解压到plugins目录 使用 `plugins.nonebot_plugin_dailysign.models` 进行导入
安装到pip 直接使用 包名 导入
