### ISSUE TITLE
多对多关系添加问题

### ISSUE THREAD

**Issue by mintianzan** [kexue-z/nonebot-plugin-tortoise-orm#3]
![微信截图_20230911103836](https://github.com/kexue-z/nonebot-plugin-tortoise-orm/assets/140377173/bd7e6943-d65b-4069-8389-6117f8f7503f)
![微信截图_20230911103856](https://github.com/kexue-z/nonebot-plugin-tortoise-orm/assets/140377173/ac48eabe-6117-4aa3-b71d-8783b6b65780)
和#1 的情况不太一样，我这里直接使用models出现问题

**Comment by mintianzan** [comment]
草，是因为我给数据库改了名，这里应该用新名字，跟随addmodel的参数db_name

**Comment by kexue-z** [comment]
啊这
